/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './presentation/routes/__root'
import { Route as HousesRouteRouteImport } from './presentation/routes/houses/route'
import { Route as IndexRouteImport } from './presentation/routes/index'
import { Route as HousesIndexRouteImport } from './presentation/routes/houses/index'
import { Route as ContentIndexRouteImport } from './presentation/routes/content/index'
import { Route as HousesCreateRouteImport } from './presentation/routes/houses/create'
import { Route as ContentCreateRouteImport } from './presentation/routes/content/create'
import { Route as ContentContactsRouteImport } from './presentation/routes/content/contacts'
import { Route as ContentInfoSectionsIndexRouteImport } from './presentation/routes/content/info-sections/index'
import { Route as HousesEditHouseIdRouteImport } from './presentation/routes/houses/edit.$houseId'
import { Route as ContentInfoSectionsCreateRouteImport } from './presentation/routes/content/info-sections/create'
import { Route as ContentEditServiceIdRouteImport } from './presentation/routes/content/edit.$serviceId'
import { Route as ContentInfoSectionsEditInfoSectionIdRouteImport } from './presentation/routes/content/info-sections/edit.$infoSectionId'

const HousesRouteRoute = HousesRouteRouteImport.update({
  id: '/houses',
  path: '/houses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesIndexRoute = HousesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HousesRouteRoute,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesCreateRoute = HousesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => HousesRouteRoute,
} as any)
const ContentCreateRoute = ContentCreateRouteImport.update({
  id: '/content/create',
  path: '/content/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentContactsRoute = ContentContactsRouteImport.update({
  id: '/content/contacts',
  path: '/content/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentInfoSectionsIndexRoute =
  ContentInfoSectionsIndexRouteImport.update({
    id: '/content/info-sections/',
    path: '/content/info-sections/',
    getParentRoute: () => rootRouteImport,
  } as any)
const HousesEditHouseIdRoute = HousesEditHouseIdRouteImport.update({
  id: '/edit/$houseId',
  path: '/edit/$houseId',
  getParentRoute: () => HousesRouteRoute,
} as any)
const ContentInfoSectionsCreateRoute =
  ContentInfoSectionsCreateRouteImport.update({
    id: '/content/info-sections/create',
    path: '/content/info-sections/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContentEditServiceIdRoute = ContentEditServiceIdRouteImport.update({
  id: '/content/edit/$serviceId',
  path: '/content/edit/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentInfoSectionsEditInfoSectionIdRoute =
  ContentInfoSectionsEditInfoSectionIdRouteImport.update({
    id: '/content/info-sections/edit/$infoSectionId',
    path: '/content/info-sections/edit/$infoSectionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/houses': typeof HousesRouteRouteWithChildren
  '/content/contacts': typeof ContentContactsRoute
  '/content/create': typeof ContentCreateRoute
  '/houses/create': typeof HousesCreateRoute
  '/content/': typeof ContentIndexRoute
  '/houses/': typeof HousesIndexRoute
  '/content/edit/$serviceId': typeof ContentEditServiceIdRoute
  '/content/info-sections/create': typeof ContentInfoSectionsCreateRoute
  '/houses/edit/$houseId': typeof HousesEditHouseIdRoute
  '/content/info-sections/': typeof ContentInfoSectionsIndexRoute
  '/content/info-sections/edit/$infoSectionId': typeof ContentInfoSectionsEditInfoSectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/content/contacts': typeof ContentContactsRoute
  '/content/create': typeof ContentCreateRoute
  '/houses/create': typeof HousesCreateRoute
  '/content': typeof ContentIndexRoute
  '/houses': typeof HousesIndexRoute
  '/content/edit/$serviceId': typeof ContentEditServiceIdRoute
  '/content/info-sections/create': typeof ContentInfoSectionsCreateRoute
  '/houses/edit/$houseId': typeof HousesEditHouseIdRoute
  '/content/info-sections': typeof ContentInfoSectionsIndexRoute
  '/content/info-sections/edit/$infoSectionId': typeof ContentInfoSectionsEditInfoSectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/houses': typeof HousesRouteRouteWithChildren
  '/content/contacts': typeof ContentContactsRoute
  '/content/create': typeof ContentCreateRoute
  '/houses/create': typeof HousesCreateRoute
  '/content/': typeof ContentIndexRoute
  '/houses/': typeof HousesIndexRoute
  '/content/edit/$serviceId': typeof ContentEditServiceIdRoute
  '/content/info-sections/create': typeof ContentInfoSectionsCreateRoute
  '/houses/edit/$houseId': typeof HousesEditHouseIdRoute
  '/content/info-sections/': typeof ContentInfoSectionsIndexRoute
  '/content/info-sections/edit/$infoSectionId': typeof ContentInfoSectionsEditInfoSectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/houses'
    | '/content/contacts'
    | '/content/create'
    | '/houses/create'
    | '/content/'
    | '/houses/'
    | '/content/edit/$serviceId'
    | '/content/info-sections/create'
    | '/houses/edit/$houseId'
    | '/content/info-sections/'
    | '/content/info-sections/edit/$infoSectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/content/contacts'
    | '/content/create'
    | '/houses/create'
    | '/content'
    | '/houses'
    | '/content/edit/$serviceId'
    | '/content/info-sections/create'
    | '/houses/edit/$houseId'
    | '/content/info-sections'
    | '/content/info-sections/edit/$infoSectionId'
  id:
    | '__root__'
    | '/'
    | '/houses'
    | '/content/contacts'
    | '/content/create'
    | '/houses/create'
    | '/content/'
    | '/houses/'
    | '/content/edit/$serviceId'
    | '/content/info-sections/create'
    | '/houses/edit/$houseId'
    | '/content/info-sections/'
    | '/content/info-sections/edit/$infoSectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HousesRouteRoute: typeof HousesRouteRouteWithChildren
  ContentContactsRoute: typeof ContentContactsRoute
  ContentCreateRoute: typeof ContentCreateRoute
  ContentIndexRoute: typeof ContentIndexRoute
  ContentEditServiceIdRoute: typeof ContentEditServiceIdRoute
  ContentInfoSectionsCreateRoute: typeof ContentInfoSectionsCreateRoute
  ContentInfoSectionsIndexRoute: typeof ContentInfoSectionsIndexRoute
  ContentInfoSectionsEditInfoSectionIdRoute: typeof ContentInfoSectionsEditInfoSectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/houses': {
      id: '/houses'
      path: '/houses'
      fullPath: '/houses'
      preLoaderRoute: typeof HousesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses/': {
      id: '/houses/'
      path: '/'
      fullPath: '/houses/'
      preLoaderRoute: typeof HousesIndexRouteImport
      parentRoute: typeof HousesRouteRoute
    }
    '/content/': {
      id: '/content/'
      path: '/content'
      fullPath: '/content/'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses/create': {
      id: '/houses/create'
      path: '/create'
      fullPath: '/houses/create'
      preLoaderRoute: typeof HousesCreateRouteImport
      parentRoute: typeof HousesRouteRoute
    }
    '/content/create': {
      id: '/content/create'
      path: '/content/create'
      fullPath: '/content/create'
      preLoaderRoute: typeof ContentCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/contacts': {
      id: '/content/contacts'
      path: '/content/contacts'
      fullPath: '/content/contacts'
      preLoaderRoute: typeof ContentContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/info-sections/': {
      id: '/content/info-sections/'
      path: '/content/info-sections'
      fullPath: '/content/info-sections/'
      preLoaderRoute: typeof ContentInfoSectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses/edit/$houseId': {
      id: '/houses/edit/$houseId'
      path: '/edit/$houseId'
      fullPath: '/houses/edit/$houseId'
      preLoaderRoute: typeof HousesEditHouseIdRouteImport
      parentRoute: typeof HousesRouteRoute
    }
    '/content/info-sections/create': {
      id: '/content/info-sections/create'
      path: '/content/info-sections/create'
      fullPath: '/content/info-sections/create'
      preLoaderRoute: typeof ContentInfoSectionsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/edit/$serviceId': {
      id: '/content/edit/$serviceId'
      path: '/content/edit/$serviceId'
      fullPath: '/content/edit/$serviceId'
      preLoaderRoute: typeof ContentEditServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/info-sections/edit/$infoSectionId': {
      id: '/content/info-sections/edit/$infoSectionId'
      path: '/content/info-sections/edit/$infoSectionId'
      fullPath: '/content/info-sections/edit/$infoSectionId'
      preLoaderRoute: typeof ContentInfoSectionsEditInfoSectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HousesRouteRouteChildren {
  HousesCreateRoute: typeof HousesCreateRoute
  HousesIndexRoute: typeof HousesIndexRoute
  HousesEditHouseIdRoute: typeof HousesEditHouseIdRoute
}

const HousesRouteRouteChildren: HousesRouteRouteChildren = {
  HousesCreateRoute: HousesCreateRoute,
  HousesIndexRoute: HousesIndexRoute,
  HousesEditHouseIdRoute: HousesEditHouseIdRoute,
}

const HousesRouteRouteWithChildren = HousesRouteRoute._addFileChildren(
  HousesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HousesRouteRoute: HousesRouteRouteWithChildren,
  ContentContactsRoute: ContentContactsRoute,
  ContentCreateRoute: ContentCreateRoute,
  ContentIndexRoute: ContentIndexRoute,
  ContentEditServiceIdRoute: ContentEditServiceIdRoute,
  ContentInfoSectionsCreateRoute: ContentInfoSectionsCreateRoute,
  ContentInfoSectionsIndexRoute: ContentInfoSectionsIndexRoute,
  ContentInfoSectionsEditInfoSectionIdRoute:
    ContentInfoSectionsEditInfoSectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
