/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/presentation/routes/__root'
import { Route as IndexRouteImport } from './app/presentation/routes/index'
import { Route as HousesIndexRouteImport } from './app/presentation/routes/houses/index'
import { Route as HousesCreateRouteImport } from './app/presentation/routes/houses/create'
import { Route as HousesEditHouseIdRouteImport } from './app/presentation/routes/houses/edit.$houseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesIndexRoute = HousesIndexRouteImport.update({
  id: '/houses/',
  path: '/houses/',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesCreateRoute = HousesCreateRouteImport.update({
  id: '/houses/create',
  path: '/houses/create',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesEditHouseIdRoute = HousesEditHouseIdRouteImport.update({
  id: '/houses/edit/$houseId',
  path: '/houses/edit/$houseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/houses/create': typeof HousesCreateRoute
  '/houses/': typeof HousesIndexRoute
  '/houses/edit/$houseId': typeof HousesEditHouseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/houses/create': typeof HousesCreateRoute
  '/houses': typeof HousesIndexRoute
  '/houses/edit/$houseId': typeof HousesEditHouseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/houses/create': typeof HousesCreateRoute
  '/houses/': typeof HousesIndexRoute
  '/houses/edit/$houseId': typeof HousesEditHouseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/houses/create' | '/houses/' | '/houses/edit/$houseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/houses/create' | '/houses' | '/houses/edit/$houseId'
  id: '__root__' | '/' | '/houses/create' | '/houses/' | '/houses/edit/$houseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HousesCreateRoute: typeof HousesCreateRoute
  HousesIndexRoute: typeof HousesIndexRoute
  HousesEditHouseIdRoute: typeof HousesEditHouseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses/': {
      id: '/houses/'
      path: '/houses'
      fullPath: '/houses/'
      preLoaderRoute: typeof HousesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses/create': {
      id: '/houses/create'
      path: '/houses/create'
      fullPath: '/houses/create'
      preLoaderRoute: typeof HousesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses/edit/$houseId': {
      id: '/houses/edit/$houseId'
      path: '/houses/edit/$houseId'
      fullPath: '/houses/edit/$houseId'
      preLoaderRoute: typeof HousesEditHouseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HousesCreateRoute: HousesCreateRoute,
  HousesIndexRoute: HousesIndexRoute,
  HousesEditHouseIdRoute: HousesEditHouseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
